name: pmp_english
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  json_serializable: ^6.8.0
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  get_it: ^8.0.2
  smooth_page_indicator: ^1.2.0+3
  flutter_dotenv: ^5.2.1
  # supabase_flutter: ^2.8.0
  youtube_player_flutter: ^9.1.2
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  permission_handler: ^11.3.1
  gal: ^2.3.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  just_audio: ^0.9.42
  firebase_core: ^3.12.0
  firebase_crashlytics: ^4.1.4
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.17
  # flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  http: ^1.3.0
  drift: ^2.28.0
  drift_flutter: ^0.2.5
  confetti: ^0.8.0
  internet_connection_checker: ^3.0.1
  string_similarity: ^2.1.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.3
  fl_chart: ^1.1.0
  record: ^6.1.2
  supabase_flutter: ^2.10.3
  flutter_widget_from_html: ^0.16.1
  intl_utils: ^2.8.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.8
  flutter_launcher_icons: ^0.14.2
  drift_dev: ^2.27.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21

  image_path: "logo/app_logo.png" # Main app icon
  adaptive_icon_foreground: "logo/app_logo.png"
  adaptive_icon_background: "#000000"

  android_notification_icon: "logo/ic_notification.png" # Notification icon

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .envs/
    - assets/images/
    - assets/images/profiles/
    - assets/explanation/
    - assets/subtitles/
    - assets/days/day_01/
    - assets/days/day_02/
    - assets/days/day_03/
    - assets/days/day_04/
    - assets/days/day_05/
    - assets/days/day_06/
    - assets/days/day_07/
    - assets/days/day_08/
    - assets/days/day_09/
    - assets/days/day_10/
    - assets/days/day_11/
    - assets/days/day_12/
    - assets/days/day_13/
    - assets/days/day_14/
    - assets/days/day_15/
    - assets/days/day_16/
    - assets/days/day_17/
    - assets/days/day_18/
    - assets/days/day_19/
    - assets/days/day_20/
    - assets/days/day_21/
    - assets/days/day_22/
    - assets/days/day_23/
    - assets/days/day_24/
    - assets/days/day_25/
    - assets/days/day_26/
    - assets/days/day_27/
    - assets/days/day_28/
    - assets/days/day_29/
    - assets/days/day_30/
    - assets/zendaya/
    - assets/important_of_social_health/
    - assets/paul_rudd_interview/
    - assets/going_viral_taugh_me/
    - assets/spoken_patterns/day_01/
    - assets/spoken_patterns/day_02/
    - assets/spoken_patterns/day_03/
    - assets/spoken_patterns/day_04/
    - assets/spoken_patterns/day_05/
    - assets/spoken_patterns/day_06/
    - assets/spoken_patterns/day_07/
    - assets/spoken_patterns/day_08/
    - assets/spoken_patterns/day_09/
    - assets/spoken_patterns/day_10/
    - assets/spoken_patterns/day_11/
    - assets/spoken_patterns/day_12/
    - assets/spoken_patterns/day_13/
    - assets/spoken_patterns/day_14/
    - assets/spoken_patterns/day_15/
    - assets/spoken_patterns/day_16/
    - assets/spoken_patterns/day_17/
    - assets/spoken_patterns/day_18/
    - assets/spoken_patterns/day_19/
    - assets/spoken_patterns/day_20/
    - assets/spoken_patterns/day_21/
    - assets/spoken_patterns/day_22/
    - assets/spoken_patterns/day_23/
    - assets/spoken_patterns/day_24/
    - assets/spoken_patterns/day_25/
    - assets/spoken_patterns/day_26/
    - assets/spoken_patterns/day_27/
    - assets/spoken_patterns/day_28/
    - assets/spoken_patterns/day_29/
    - assets/spoken_patterns/day_30/
    - logo/
    # - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ArchivoBlack Regular
      fonts:
        - asset: fonts/ArchivoBlack-Regular.ttf

    - family: MM Lyrics Bold
      fonts:
        - asset: fonts/mm/NotoSansMyanmar-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  output_dir: lib/l10n/generated
