// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA486A7Ut8px5y6Ne4prGk5u89duFhjQyU',
    appId: '1:1022138253974:web:64c99b4617e29edc4b78b7',
    messagingSenderId: '1022138253974',
    projectId: 'pmp-english-6d906',
    authDomain: 'pmp-english-6d906.firebaseapp.com',
    storageBucket: 'pmp-english-6d906.firebasestorage.app',
    measurementId: 'G-JPEMLDVNP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmxJKh6-snY5UEoY-umkHpYMdFM5-ixUY',
    appId: '1:1022138253974:android:4ae97c59ba15e01a4b78b7',
    messagingSenderId: '1022138253974',
    projectId: 'pmp-english-6d906',
    storageBucket: 'pmp-english-6d906.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsn7Fz7_QVHTF1iXky4D6iGAdtLaBPIhs',
    appId: '1:1022138253974:ios:d07a8612c4fe65884b78b7',
    messagingSenderId: '1022138253974',
    projectId: 'pmp-english-6d906',
    storageBucket: 'pmp-english-6d906.firebasestorage.app',
    iosBundleId: 'com.tzkenglishlab.pmpEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsn7Fz7_QVHTF1iXky4D6iGAdtLaBPIhs',
    appId: '1:1022138253974:ios:d07a8612c4fe65884b78b7',
    messagingSenderId: '1022138253974',
    projectId: 'pmp-english-6d906',
    storageBucket: 'pmp-english-6d906.firebasestorage.app',
    iosBundleId: 'com.tzkenglishlab.pmpEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA486A7Ut8px5y6Ne4prGk5u89duFhjQyU',
    appId: '1:1022138253974:web:038e86b5381254c44b78b7',
    messagingSenderId: '1022138253974',
    projectId: 'pmp-english-6d906',
    authDomain: 'pmp-english-6d906.firebaseapp.com',
    storageBucket: 'pmp-english-6d906.firebasestorage.app',
    measurementId: 'G-8C68F61M3M',
  );
}
