// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyAbgzLu2ZVonKd9QI_9iYv8tPcLl68C8uk',
  //   appId: '1:184571582087:web:2cdac277756cb9ded60a22',
  //   messagingSenderId: '184571582087',
  //   projectId: 'pmp-english-dev',
  //   authDomain: 'pmp-english-dev.firebaseapp.com',
  //   storageBucket: 'pmp-english-dev.firebasestorage.app',
  //   measurementId: 'G-9PK7LRTVTJ',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyG_Me4cKViq4fMmKwmYwi5QXZ4Z41WGQ',
    appId: '1:184571582087:android:7b68f03ec3183250d60a22',
    messagingSenderId: '184571582087',
    projectId: 'pmp-english-dev',
    storageBucket: 'pmp-english-dev.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBXk2uhdfMu3LhGvsO7bo7mPsQfWcVB4RM',
  //   appId: '1:184571582087:android:7b68f03ec3183250d60a22',
  //   messagingSenderId: '184571582087',
  //   projectId: 'pmp-english-dev',
  //   storageBucket: 'pmp-english-dev.firebasestorage.app',
  //   iosBundleId: 'com.tzkenglishlab.pmpEnglish',
  // );
}
